# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e235a1a51aaf79cbe119e1218215bbac9fc897f9e55b4ef417785eb95d56dc6c3ba9cba6d6318d98188a557abaa979c9d78ce233cab3a89a91ab6d12f7ba37f8

test:
  secret_key_base: 8729f1a18b57a15625f5a313e829e91ab888c3606a4160f31fd3d15347118a1cbcdc4c517b124bf4bfd78a2793c3d39ac37eb3209d1b11b738fa9b2541a16cc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
